### PR TITLE
README.md: fixed several glitches

### PR DESCRIPTION
**Pull request by marcelpetrick**
Fixed some typos, whitespace and the forgotten replacing of "QtBigInt".

### CODE REVIEW

**Review by EndrII — APPROVED** [review]
Thanks 
I will merge this PR later.

**Comment by EndrII** [comment]
Hm.  Auto tests look bad. I think I should be fixed build for ios and qt6 before merge this pull request

**Comment by EndrII** [comment]
@marcelpetrick please update your branch

**Comment by EndrII** [comment]
I was merged this pr manually

**Comment by marcelpetrick** [comment]
Thank you. Since you resolved it by yourself, I won't take any further actions.

**Pull request merged**
